# name: Playwright Tests
# on:
#   push:
#     branches: [ main ]
#     paths:
#       - 'Evernorth/**'
# jobs:
#   test:
#     uses: ./Evernorth-QE/.github/workflows/playwright.yml@main
name: Dispatcher
on:
  push:
    branches: [ main ]
jobs:
  call-playwright:
    uses: ./.github/workflows/playwright.yml@main
